= The Mischievous Clurichauns

== SzHb’s Notes

[arabic]
. *_T5_* Naggeneen’s Brew from *_T9_* Arisen Naggeneen, an Item that can proc all single-up buffs in 1 turn.
. *_T7_* Smelly Mushrooms from all event raids, an Item that can proc All↑↑.
. *_T6_* Bricriu’s Bow from Bricriu, an Off-hand that give Arrowstorm Off-hand skill.
. *_T8_* Amadan’s Staff from *_T8_* Amadan, an Off-hand that give Lacunus Off-hand skill.
. *_T7_* Naggeneen’s Belt from all event raids, an Accessory that makes debuffs 15% easier to apply to opponents (stack additively).

== Event Checklist (mostly from community)

=== Monsters

T8 mobs can be found in Chaos Portals.

* *_T4_* Aine
* *_T4_* Conall
* *_T4_* Finn
* *_T6_* Amergin
* *_T6_* Bricriu
* *_T6_* Cormac
* *_T8_* Beag
* *_T8_* Fergus

=== Raids ([K]-Kingdom raid, [W]-Summoning scroll, [O]-Others)

* *[K/W]* *_T7_* Naggeneen
* *[K/W]* *_T9_* Arisen Naggeneen

=== Followers

* *_T6_* Naggeneen
* *_T8_* Amadan
* *_T9_* Arisen Naggeneen

=== Bossed

Can be found in Chaos Portals.

* *_T8_* Amadan

